import v3.1.1

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,6 +1,6 @@
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(src/main.cc)
-AM_INIT_AUTOMAKE(mp3blaster, 3.1)
+AM_INIT_AUTOMAKE(mp3blaster, 3.1.1)
 
 AM_CONFIG_HEADER(config.h)
 
@@ -95,6 +95,11 @@ AC_ARG_WITH(nas,
   [ if test "$withval" = "yes" ; then WANTNAS=1
     else WANTNAS=0 ; fi ],
   [ WANTNAS=0 ])
+AC_ARG_WITH(curses,
+  [  --with-curses           Force using curses, even if ncurses found [default=no]],
+  [ if test "$withval" = "yes" ; then FORCECURSES=1
+    else FORCECURSES=0; fi],
+  [ FORCECURSES=0 ])
 AC_ARG_WITH(sidplay,
   [  --with-sidplay          Sidplayer support [default=yes]],
   [ if test "$withval" = "yes" ; then WANT_SID=1
@@ -121,12 +126,12 @@ if test "$NEWTHREAD" = "1" ; then
 	INCLUDEPTHREAD=0
 fi
 
-
 dnl Checks for libraries.
 AC_CHECK_LIB(m,main,,AC_MSG_ERROR("No libm or no cos"))
 AC_CHECK_LIB(ncurses,main,INCLUDENCURSES=1)
 AC_CHECK_LIB(curses,main,INCLUDECURSES=1)
 AC_CHECK_LIB(ossaudio,main)
+
 if test "$INCLUDEPTHREAD" = 1 ; then
 	if test "$FREEBSD" = 1 -o "$OPENBSD" = 1 ; then
   	LDFLAGS="$LDFLAGS -pthread"
@@ -195,7 +200,7 @@ AC_HEADER_STDC
 AC_CHECK_HEADERS(fcntl.h malloc.h sys/ioctl.h unistd.h errno.h)
 AC_CHECK_HEADERS(bool.h)
 AC_CHECK_HEADERS(pthread.h pthread/mit/pthread.h pth.h)
-AC_CHECK_HEADERS(ncurses/ncurses.h ncurses/curses.h ncurses.h curses.h)
+AC_CHECK_HEADERS(curses.h,HAVE_CURSES_H=1)
 AC_CHECK_HEADERS(sys/soundcard.h machine/soundcard.h soundcard.h getopt.h)
 AC_CHECK_HEADER(sys/soundcard.h,HAVE_SYS_SOUNDCARD_H=1)
 AC_CHECK_HEADER(machine/soundcard.h,HAVE_MACHINE_SOUNDCARD_H=1)
@@ -203,6 +208,18 @@ AC_CHECK_HEADER(soundcard.h,HAVE_SOUNDCARD_H=1)
 AC_CHECK_HEADER(mysql/mysql.h,HAVE_MYSQL_MYSQL_H=1)
 AC_CHECK_HEADER(mysql.h,HAVE_MYSQL_H=1)
 
+dnl Forcing curses ?
+if test "$FORCECURSES" = "1" ; then
+     echo "Not checking for ncurses"
+     INCLUDENCURSES=0;
+     if test "$INCLUDECURSES" = 0 || test "$HAVE_CURSES_H" = 0; then
+	echo "***********"
+	echo "You want to force using curses, but curses is not found."
+	exit 1
+    fi
+else
+    AC_CHECK_HEADERS(ncurses/ncurses.h ncurses/curses.h ncurses.h)
+fi
 if test "$HAVE_SYS_SOUNDCARD_H" = 1 ; then
       AC_DEFINE_UNQUOTED(SOUNDCARD_HEADERFILE, <sys/soundcard.h>)
 elif test "$HAVE_MACHINE_SOUNDCARD_H" = 1 ; then
@@ -312,7 +329,9 @@ if test -f /usr/include/__math.h -a "`grep 'long long int __p = (long long int) 
 fi
 dnl Even the script above is not foolproof. Since I can't tell the difference
 dnl in speed with or without this define, just define it.
-CXXFLAGS="$CXXFLAGS -D__NO_MATH_INLINES"
+dnl 2002/03/16: removed this, if you still use an ancient gcc-version and the
+dnl check doesn't work, enable this yourself..
+dnl CXXFLAGS="$CXXFLAGS -D__NO_MATH_INLINES"
 
 dnl check for Network Audio System library
 
