import v3.0p8

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,6 +1,8 @@
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(src/main.cc)
-AM_INIT_AUTOMAKE(mp3blaster, 3.0p7)
+AM_INIT_AUTOMAKE(mp3blaster, 3.0p8)
+
+AM_CONFIG_HEADER(config.h)
 
 dnl Checks for programs.
 AC_PROG_CC
@@ -24,11 +26,15 @@ if test "`uname -s`" = "FreeBSD" ; then
   FREEBSD=1
   LDFLAGS="-L/usr/local/lib $LDFLAGS"
   CPPFLAGS="-I/usr/local/include $CPPFLAGS"
-	AC_DEFINE(AUDIO_NONBLOCKING)
+  AC_DEFINE(AUDIO_NONBLOCKING)
 fi
 
 
 dnl Check for additional paths to include-files and directories first 
+AC_ARG_WITH(cxxflags,
+  [  --with-cxxflags         Override default compiler flags],
+	[ CXXFLAGS="$withval " ],
+	[ CXXFLAGS="-O2 -Wall -Wstrict-prototypes -W -fno-strength-reduce " ])
 AC_ARG_WITH(mysql-includes,
   [  --with-mysql-includes   Specify location of MySQL headers],
   [ CPPFLAGS="$CPPFLAGS -I$withval" ])
@@ -47,59 +53,110 @@ AC_ARG_WITH(nas-libs,
 AC_ARG_WITH(extra-libs,
   [  --with-extra-libs       Specify location of extra libs],
   [ LDFLAGS="$LDFLAGS $withval" ])
+AC_ARG_WITH(pthreads,
+  [  --with-pthreads         Use pthreads [default=yes]],
+  [ if test "$withval" = "yes" ; then INCLUDEPTHREAD=1
+    else INCLUDEPTHREAD=0; fi ],
+  [ INCLUDEPTHREAD=1 ])
+dnl silently auto-disable pthreads if pth is chosen.
+AC_ARG_WITH(pth,
+  [  --with-pth              Experimental support for pth lib [default=no]],
+  [ if test "$withval" = "yes" ; then HAVE_PTH="yes" ; INCLUDEPTHREAD=0
+    else HAVE_PTH="no" ; fi ],
+  [ HAVE_PTH="no" ])
+AC_ARG_WITH(oggvorbis,
+  [  --with-oggvorbis        Beta support for ogg vorbis format [default=yes]],
+  [ if test "$withval" = "yes" ; then HAVE_OGG="yes" ; 
+    else HAVE_OGG="no"; fi ],
+  [ HAVE_OGG="yes" ])
+AC_ARG_WITH(mysql,
+  [  --with-mysql            Mp3tag with alpha MySQL support [default=no]],
+  [ if test "$withval" = "yes" ; then HAVE_MYSQL="yes"
+    else HAVE_MYSQL="no"; fi ],
+  [ HAVE_MYSQL="no" ])
+AC_ARG_WITH(nas,
+  [  --with-nas              Network Audio System [default=no]],
+  [ if test "$withval" = "yes" ; then WANTNAS=1
+    else WANTNAS=0 ; fi ],
+  [ WANTNAS=0 ])
+AC_ARG_WITH(sidplay,
+  [  --with-sidplay          Sidplayer support [default=yes]],
+  [ if test "$withval" = "yes" ; then WANT_SID=1
+    else WANT_SID=0 ; fi ],
+  [ WANT_SID=1 ])
 AC_ARG_ENABLE(static,
   [  --enable-static         Build static binaries instead [default=no]],
-	[ LDFLAGS="$LDFLAGS -static" ])
+  [ if test "$enableval" = "yes" ; then
+      LDFLAGS="$LDFLAGS -static" ; HAVE_STATIC="yes"
+    else HAVE_STATIC="no" ; fi ],
+  [ HAVE_STATIC="no" ])
 AC_ARG_ENABLE(newthreads,
-	[  --enable-newthreads     New (very experimental) buffering [default=no]],
-	[ NEWTHREAD=1 ])
-AC_ARG_ENABLE(pthreads,
-	[  --enable-pthreads       Use pthreads [default=yes]],
-	[ if "$enableval"="yes" ; then INCLUDEPTHREAD=1 ; else INCLUDEPTHREAD=0; fi ],
-	[ INCLUDEPTHREAD=1 ])
-AC_ARG_ENABLE(pth,
-	[  --enable-pth            Experimental support for pth lib [default=no]],
-	  [ WANT_PTH=1; INCLUDEPTHREAD=0 ])
+  [  --enable-newthreads     New (very experimental) buffering [default=no]],
+  [ NEWTHREAD=1 ])
 
-if test "$INCLUDEPTHREAD" = "0" ; then
-	echo "***** NO PTHREADS *****"
-fi
 dnl Checks for libraries.
 AC_CHECK_LIB(m,main,,AC_MSG_ERROR("No libm or no cos"))
 AC_CHECK_LIB(ncurses,main,INCLUDENCURSES=1)
 AC_CHECK_LIB(curses,main,INCLUDECURSES=1)
-AC_CHECK_LIB(mysqlclient,main,HAVE_MYSQL=1)
-AC_CHECK_LIB(sidplay, main, HAVE_SID=1)
 AC_CHECK_LIB(ossaudio,main)
 if test "$FREEBSD" = 1 -a "$INCLUDEPTHREAD" = 1 ; then
-	LDFLAGS="$LDFLAGS -pthread"
+  LDFLAGS="$LDFLAGS -pthread"
 elif test "$INCLUDEPTHREAD" = 1 ; then
   AC_CHECK_LIB(pthread,main,,INCLUDEPTHREAD=0)
 fi
 
-dnl Check PTH support
-if test "$WANT_PTH" = "1" ; then
-	if test -z "`pth-config --version 2>/dev/null`" ; then
-		echo "***********"
-		echo "You want PTH support but pth-config is not in your path."
-		exit 1
-	fi
-	
-	if ! test "$INCLUDEPTHREAD" = "0" ; then
-		echo "***********"
-		echo "You can't use pthread *and* pth, disable one of both."
-		exit 1
-	fi
+if test "$HAVE_OGG" = "yes" ; then
+  AC_CHECK_LIB(vorbisfile,main,HAVE_OGG="yes",HAVE_OGG="no",-lvorbis)
+  if test "$HAVE_OGG" = "yes" ; then
+    OGG_LIBS="-lvorbisfile -lvorbis"
+		AC_SUBST(OGG_LIBS)
+    AC_DEFINE(INCLUDE_OGG)
+  fi
+fi
 
-	LDFLAGS="$LDFLAGS `pth-config --ldflags`"
-	LIBS="$LIBS `pth-config --libs`"
-	CXXFLAGS="$CXXFLAGS -I`pth-config --includedir`"
-	dnl set CPPFLAGS so AC_CHECK_HEADER can find pth.h
-	CPPFLAGS="$CPPFLAGS -I`pth-config --includedir`"
-	AC_DEFINE(LIBPTH)
-	echo "*************"
-	echo "PTH support enabled. Mail testresults to bram@mp3blaster.avontuur.org."
-	echo "*************"
+dnl Check MySQL support
+if test "$HAVE_MYSQL" = "yes" ; then
+  AC_CHECK_LIB(mysqlclient,main,HAVE_MYSQL="yes",HAVE_MYSQL="no")
+  if test "$HAVE_MYSQL" = "yes" ; then
+    if test "$HAVE_MYSQL_MYSQL_H" = 1 ; then
+      MYSQL_H="mysql/mysql.h"
+    elif test "$HAVE_MYSQL_H" = 1 ; then
+      MYSQL_H="mysql.h"
+    else
+      MYSQL_H=""
+    fi
+    if test -z "$MYSQL_H" ; then
+      HAVE_MYSQL="no"
+    else
+      LIBMYSQL="-lmysqlclient"
+       AC_SUBST(LIBMYSQL)
+      AC_DEFINE(WANT_MYSQL)
+      AC_DEFINE_UNQUOTED(MYSQL_H, <$MYSQL_H>)
+    fi
+  fi
+fi
+
+dnl Check PTH support
+if test "$HAVE_PTH" = "yes" ; then
+  if test -z "`pth-config --version 2>/dev/null`" ; then
+    echo "***********"
+    echo "You want PTH support but pth-config is not in your path."
+    exit 1
+  fi
+  
+  if ! test "$INCLUDEPTHREAD" = "0" ; then
+    echo "***********"
+    echo "You can't use pthread *and* pth, disable one of both."
+    exit 1
+  fi
+
+  LDFLAGS="$LDFLAGS `pth-config --ldflags`"
+  LIBS="$LIBS `pth-config --libs`"
+  CXXFLAGS="$CXXFLAGS -I`pth-config --includedir`"
+  dnl set CPPFLAGS so AC_CHECK_HEADER can find pth.h
+  CPPFLAGS="$CPPFLAGS -I`pth-config --includedir`"
+  AC_DEFINE(LIBPTH)
+  HAVE_PTH="yes"
 fi
 
 
@@ -110,19 +167,23 @@ AC_CHECK_HEADERS(bool.h)
 AC_CHECK_HEADERS(pthread.h pthread/mit/pthread.h pth.h)
 AC_CHECK_HEADERS(ncurses/ncurses.h ncurses/curses.h ncurses.h curses.h)
 AC_CHECK_HEADERS(sys/soundcard.h machine/soundcard.h soundcard.h getopt.h)
+AC_CHECK_HEADER(sys/soundcard.h,HAVE_SYS_SOUNDCARD_H=1)
+AC_CHECK_HEADER(machine/soundcard.h,HAVE_MACHINE_SOUNDCARD_H=1)
+AC_CHECK_HEADER(soundcard.h,HAVE_SOUNDCARD_H=1)
 AC_CHECK_HEADER(mysql/mysql.h,HAVE_MYSQL_MYSQL_H=1)
 AC_CHECK_HEADER(mysql.h,HAVE_MYSQL_H=1)
 
+if test "$HAVE_SYS_SOUNDCARD_H" = 1 ; then
+      AC_DEFINE_UNQUOTED(SOUNDCARD_HEADERFILE, <sys/soundcard.h>)
+elif test "$HAVE_MACHINE_SOUNDCARD_H" = 1 ; then
+      AC_DEFINE_UNQUOTED(SOUNDCARD_HEADERFILE, <machine/soundcard.h>)
+elif test "$HAVE_SOUNDCARD_H" = 1 ; then
+      AC_DEFINE_UNQUOTED(SOUNDCARD_HEADERFILE, <soundcard.h>)
+else
+	AC_MSG_ERROR(No OSS include file (soundcard.h) found, bailing out.)
+fi
+
 dnl Extra features 
-AC_ARG_WITH(mysql,
-  [  --with-mysql            mp3tag with MySQL support (alpha, default=no)], \
-  if test "$withval" = "yes" ; then WANT_MYSQL=1 ; else WANT_MYSQL=0; fi)
-AC_ARG_WITH(nas,
-  [  --with-nas              network audio system (default=no)], \
-  if test "$withval" = "yes" ; then WANTNAS=1 ; else WANTNAS=0 ; fi)
-AC_ARG_WITH(sidplay,
-  [  --with-sidplay          sidplayer support (default=no)], \
-  if test "$withval" = "yes" ; then WANTSID=1 ; else WANTSID=0 ; fi)
 AC_ARG_WITH(modules,
   [  --with-modules=LIST     Add modules as a : separated list of names],
   [ mp3b_mods=`echo "$withval"|sed -e s+':'+' '+g`
@@ -142,45 +203,25 @@ EOF
 EOF
 ])
 
-dnl Check MySQL support
-if test "$WANT_MYSQL" = "1" ; then
-  if test "$HAVE_MYSQL_MYSQL_H" = 1 ; then
-    MYSQL_H="mysql/mysql.h"
-  elif test "$HAVE_MYSQL_H" = 1 ; then
-    MYSQL_H="mysql.h"
-  else
-    MYSQL_H=""
-  fi
-  if test -z "$HAVE_MYSQL" -o -z "$MYSQL_H" ; then
-    echo "*** MySQL support for mp3tag disabled: Library/includes not found."
-  else
-  	LIBMYSQL="-lmysqlclient"
- 	AC_SUBST(LIBMYSQL)
-	AC_DEFINE(WANT_MYSQL)
-	AC_DEFINE_UNQUOTED(MYSQL_H, <$MYSQL_H>)
-  	echo "*** MySQL support for mp3tag enabled."
-  fi
-fi
-
 if ! test -z "$NEWTHREAD" ; then
-	echo "***********"
-	echo "Enabling experimental 'newthreads' buffered playback support."
-	AC_DEFINE(NEWTHREAD)
+  echo "***********"
+  echo "Enabling experimental 'newthreads' buffered playback support."
+  AC_DEFINE(NEWTHREAD)
 fi
 
 dnl Check SID support
+HAVE_SID="no"
 if test "$WANT_SID" = 1 ; then
-  if test "$HAVE_SID" = 1 ; then
+  AC_CHECK_LIB(sidplay, main,HAVE_SID="yes",HAVE_SID="no")
+  if test "$HAVE_SID" = "yes" ; then
     SID_LIBS="-lsidplay"
     AC_DEFINE(HAVE_SIDPLAYER)
-	AC_SUBST(SID_LIBS)
-    echo "*** Sidplayer support enabled."
-  else
-    echo "*** Sidplayer library not found."
+    AC_SUBST(SID_LIBS)
   fi
 fi
 
 dnl Check NAS support
+HAVE_NAS="no"
 if test "$WANTNAS" = "1" ; then
   AC_PATH_XTRA
   dnl X_CFLAGS are needed to find audio/audiolib.h on many systems
@@ -200,11 +241,10 @@ if test "$WANTNAS" = "1" ; then
     AC_DEFINE(HAVE_NASPLAYER)
     AC_SUBST(NAS_LIBS)
     AC_SUBST(NAS_CFLAGS)
-    echo "************************"
-    echo "* NAS support included *"
-    echo "************************"
+    HAVE_NAS="yes"
   fi
 fi
+
 if test "`uname -s`" = "OpenBSD" ; then
   SOUNDDEV="/dev/audio"
 else
@@ -215,30 +255,31 @@ AC_DEFINE_UNQUOTED(SOUND_DEVICE, "$SOUNDDEV")
 if test "$INCLUDEPTHREAD" = 1 ; then
   if test "$FREEBSD" = "1" ; then
     LDFLAGS="$LDFLAGS -pthread"
-		AC_DEFINE(_THREAD_SAFE)
-  	AC_DEFINE(_REENTRANT)
+    AC_DEFINE(_THREAD_SAFE)
+    AC_DEFINE(_REENTRANT)
   else
-		LIBS="$LIBS -lpthread"
-		#Is _REENTRANT only needed for Linux? Is it still needed? Where is the
-		#documentation about _REENTRANT???? I've read in a newsgroup _THREAD_SAFE
-		#should be used for FreeBSD, _REENTRANT for linux....dunno why.
-  	AC_DEFINE(_REENTRANT)
+    LIBS="$LIBS -lpthread"
+    #Is _REENTRANT only needed for Linux? Is it still needed? Where is the
+    #documentation about _REENTRANT???? I've read in a newsgroup _THREAD_SAFE
+    #should be used for FreeBSD, _REENTRANT for linux....dunno why.
+    AC_DEFINE(_REENTRANT)
   fi
   AC_DEFINE(PTHREADEDMPEG)
   dnl AC_DEFINE(THREAD_2)
-elif ! test "$WANT_PTH" = "1" ; then
-	echo "Sorry, pthread OR pth support is now required!"
-	exit 1;
+elif test "$HAVE_PTH" = "no" ; then
+  echo "Sorry, either libpthread OR libpth is required."
+  exit 1;
 fi
 
 if test "$INCLUDENCURSES" = 1 ; then
-  LIBS="$LIBS -lncurses"
+  NCURSES_LIBS="-lncurses"
 elif test "$INCLUDECURSES" = 1 ; then
-  LIBS="$LIBS -lcurses"
+  NCURSES_LIBS="-lcurses"
 else
   echo 'You need a decent ncurses (called curses on OpenBSD) library!'
   exit 1
 fi
+AC_SUBST(NCURSES_LIBS)
 
 dnl A check for a particular __math.h file that causes sigsegv's in combination
 dnl with gcc 2.7.*  / egcs-1.1.1 or older versions
@@ -258,24 +299,25 @@ LIBNMIXER="-lnmixer"
 AC_SUBST(LIBMPEGSOUND)
 AC_SUBST(LIBNMIXER)
 
-CXXFLAGS="$CXXFLAGS -g -Wall -Wstrict-prototypes -W -fno-strength-reduce "
 SRCDIRS="mpegsound nmixer src doc"
 AC_SUBST(SRCDIRS)
 AC_OUTPUT(src/Makefile mpegsound/Makefile Makefile nmixer/Makefile doc/Makefile)
 
-cat << EOF
+PTHREADS_OR_PTH="pthreads"
+if test "$HAVE_PTH" = "yes" ; then PTHREADS_OR_PTH="pth" ; fi
+
+AC_MSG_RESULT([
+Building summary:
+static binaries    $HAVE_STATIC
+ogg-vorbis         $HAVE_OGG
+mysql mp3tag       $HAVE_MYSQL
+libpth             $HAVE_PTH
+pthreads or pth    $PTHREADS_OR_PTH
+nas                $HAVE_NAS
+sidplayer          $HAVE_SID
+
 *****************************************************************************
-* Before asking questions, be sure to read the FAQ included in the source   *
-* or read it here:                                                          *
-*                                                                           *
-* http://www.stack.nl/~brama/mp3blaster/?page=faq                           *
-*                                                                           *
-* Custom include/libpaths can be given with --with-extra-libs and           *
-* --with-extra-includes                                                     *
-*                                                                           *
-* Mail bugs/development issues to mp3blaster-devel@stack.nl please!         *
-*                                                                           *
-* I wish you lots of listening pleasure!                                    *
-* Bram (bram@mp3blaster.avontuur.org) http://www.stack.nl/~brama/           *
+* Questions? Read ./FAQ or http://www.stack.nl/~brama/mp3blaster/?page=faq  *
+* Mail bugs/development issues to mp3blaster-devel@stack.nl.                *
 *****************************************************************************
-EOF
+])
